name: euk2_project
description: The EUK2 main project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  custom_info_window: ^1.0.1
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.1
  location: ^4.4.0
  onboarding: ^3.1.0
  introduction_screen: ^3.1.1
  shared_preferences: ^2.0.11
  flutter_bloc: ^8.1.1
  csv: ^5.0.1
  spreadsheet_decoder: ^2.1.1
  http: ^0.13.5
  rxdart: ^0.27.7
  google_maps_cluster_manager: ^3.0.0+1
  map_launcher: ^2.5.0+1
  latlong2: ^0.8.1
  flutter_svg: ^1.1.6
  url_launcher: ^6.1.10
  flutter_scroll_to_top: ^2.3.0
  internet_connection_checker: ^1.0.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0

  flutter_lints: ^2.0.0
  lint: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/map_styles/
